/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityPanel: typeof import('./src/components/ActivityPanel.vue')['default']
    AiAssistant: typeof import('./src/components/AiAssistant.vue')['default']
    AiBlocks: typeof import('./src/components/AiBlocks.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    AwesomeBar: typeof import('./src/components/AwesomeBar.vue')['default']
    Breadcrumbs: typeof import('./src/components/Breadcrumbs.vue')['default']
    ChildTable: typeof import('./src/components/ChildTable.vue')['default']
    ColumnPicker: typeof import('./src/components/ColumnPicker.vue')['default']
    ConnectionBanner: typeof import('./src/components/ConnectionBanner.vue')['default']
    ConnectionsPanel: typeof import('./src/components/ConnectionsPanel.vue')['default']
    DoctypeFieldPicker: typeof import('./src/components/DoctypeFieldPicker.vue')['default']
    DoneIcon: typeof import('./src/components/DoneIcon.vue')['default']
    DrillChart: typeof import('./src/components/DrillChart.vue')['default']
    DrillDialog: typeof import('./src/components/DrillDialog.vue')['default']
    DynamicField: typeof import('./src/components/DynamicField.vue')['default']
    EmailSettingsPanel: typeof import('./src/components/EmailSettingsPanel.vue')['default']
    FilterEditor: typeof import('./src/components/FilterEditor.vue')['default']
    FormTabSections: typeof import('./src/components/FormTabSections.vue')['default']
    GeoLocationField: typeof import('./src/components/GeoLocationField.vue')['default']
    IndiaGeoField: typeof import('./src/components/IndiaGeoField.vue')['default']
    LinkField: typeof import('./src/components/LinkField.vue')['default']
    LucideIcon: typeof import('./src/components/LucideIcon.vue')['default']
    MobileNav: typeof import('./src/components/MobileNav.vue')['default']
    MobileShell: typeof import('./src/components/MobileShell.vue')['default']
    NetworkPill: typeof import('./src/components/NetworkPill.vue')['default']
    NotificationPanel: typeof import('./src/components/NotificationPanel.vue')['default']
    NotificationSettingsPanel: typeof import('./src/components/NotificationSettingsPanel.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    ProfilePanel: typeof import('./src/components/ProfilePanel.vue')['default']
    PwaUpdatePrompt: typeof import('./src/components/PwaUpdatePrompt.vue')['default']
    QuestionConditionsPanel: typeof import('./src/components/QuestionConditionsPanel.vue')['default']
    QuestionnairePanel: typeof import('./src/components/QuestionnairePanel.vue')['default']
    RecordTasks: typeof import('./src/components/RecordTasks.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectionBar: typeof import('./src/components/SelectionBar.vue')['default']
    SettingsDialog: typeof import('./src/components/SettingsDialog.vue')['default']
    SettingsDoctypePanel: typeof import('./src/components/SettingsDoctypePanel.vue')['default']
    SettingsManagePanel: typeof import('./src/components/SettingsManagePanel.vue')['default']
    Skeleton: typeof import('./src/components/Skeleton.vue')['default']
    SortControl: typeof import('./src/components/SortControl.vue')['default']
    SortEditor: typeof import('./src/components/SortEditor.vue')['default']
    SparklesIcon: typeof import('./src/components/SparklesIcon.vue')['default']
    SyncCloudIcon: typeof import('./src/components/SyncCloudIcon.vue')['default']
    TableMultiSelectField: typeof import('./src/components/TableMultiSelectField.vue')['default']
    TaskHoverCard: typeof import('./src/components/TaskHoverCard.vue')['default']
    TopNavbar: typeof import('./src/components/TopNavbar.vue')['default']
    UserHoverCard: typeof import('./src/components/UserHoverCard.vue')['default']
    UserLinkHoverCard: typeof import('./src/components/UserLinkHoverCard.vue')['default']
    WorklistCalendar: typeof import('./src/components/WorklistCalendar.vue')['default']
  }
}
