/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiAssistant: typeof import('./src/components/AiAssistant.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    AwesomeBar: typeof import('./src/components/AwesomeBar.vue')['default']
    Breadcrumbs: typeof import('./src/components/Breadcrumbs.vue')['default']
    ChildTable: typeof import('./src/components/ChildTable.vue')['default']
    ConnectionsPanel: typeof import('./src/components/ConnectionsPanel.vue')['default']
    DynamicField: typeof import('./src/components/DynamicField.vue')['default']
    EmailSettingsPanel: typeof import('./src/components/EmailSettingsPanel.vue')['default']
    FilterEditor: typeof import('./src/components/FilterEditor.vue')['default']
    FormTabSections: typeof import('./src/components/FormTabSections.vue')['default']
    GeoLocationField: typeof import('./src/components/GeoLocationField.vue')['default']
    IndiaGeoField: typeof import('./src/components/IndiaGeoField.vue')['default']
    LinkField: typeof import('./src/components/LinkField.vue')['default']
    LucideIcon: typeof import('./src/components/LucideIcon.vue')['default']
    MobileNav: typeof import('./src/components/MobileNav.vue')['default']
    MobileShell: typeof import('./src/components/MobileShell.vue')['default']
    NotificationPanel: typeof import('./src/components/NotificationPanel.vue')['default']
    NotificationSettingsPanel: typeof import('./src/components/NotificationSettingsPanel.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    ProfilePanel: typeof import('./src/components/ProfilePanel.vue')['default']
    PwaUpdatePrompt: typeof import('./src/components/PwaUpdatePrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsDialog: typeof import('./src/components/SettingsDialog.vue')['default']
    SettingsDoctypePanel: typeof import('./src/components/SettingsDoctypePanel.vue')['default']
    Skeleton: typeof import('./src/components/Skeleton.vue')['default']
    SortEditor: typeof import('./src/components/SortEditor.vue')['default']
    SparklesIcon: typeof import('./src/components/SparklesIcon.vue')['default']
    TableMultiSelectField: typeof import('./src/components/TableMultiSelectField.vue')['default']
    TopNavbar: typeof import('./src/components/TopNavbar.vue')['default']
    UserHoverCard: typeof import('./src/components/UserHoverCard.vue')['default']
    UserLinkHoverCard: typeof import('./src/components/UserLinkHoverCard.vue')['default']
    WorklistCalendar: typeof import('./src/components/WorklistCalendar.vue')['default']
  }
}
